### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by mediacrave** [Einstein42/myq-garage#2]
I'm trying to run this script on Ubuntu and get the following error:

./myq-garage.py status
Traceback (most recent call last):
  File "./myq-garage.py", line 38, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'

Any ideas on what I could be doing wrong?

**Comment by Einstein42** [comment]
Looks like you don't have the requests package installed for python. If you have pip do 'pip install requests' Also looks like there is an ubuntu package called python-requests if you want to install it that way.

**Comment by mediacrave** [comment]
That's what I initially thought, but I'm using pip3. Not sure if that's
causing any issues. I do have the requests package

On Sun, Mar 13, 2016, 9:03 AM James notifications@github.com wrote:

> Looks like you don't have the requests package installed for python. If
> you have pip do 'pip install requests'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Einstein42/myq-garage/issues/2#issuecomment-195987489
> .
> 
> ## 
- Kevin Christopherson

**Comment by Einstein42** [comment]
Ahh I see. I haven't tested it with python3 so I'm not sure if it works or not. You can try to comment out the line 'requests.packages.urllib3.disable_warnings()' near the top of the myq-garage.py file by putting a # sign in front of the line and trying it. I will look at python3 compatibility soon.

**Comment by mediacrave** [comment]
Works perfectly, thank you!

On Sun, Mar 13, 2016, 11:28 AM James notifications@github.com wrote:

> Ahh I see. I haven't tested it with python3 so I'm not sure if it works or
> not. You can try to comment out the line
> 'requests.packages.urllib3.disable_warnings()' near the top of the
> myq-garage.py file by putting a # sign in front of the line and trying it.
> I will look at python3 compatibility soon.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Einstein42/myq-garage/issues/2#issuecomment-196016277
> .
> 
> ## 
- Kevin Christopherson

**Comment by Einstein42** [comment]
Just FYI I updated for full python3 compatibility.

**Comment by mediacrave** [comment]
Thank you!

On Sun, Mar 13, 2016, 12:50 PM James notifications@github.com wrote:

> Just FYI I updated for full python3 compatibility.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Einstein42/myq-garage/issues/2#issuecomment-196036419
> .
> 
> ## 
- Kevin Christopherson
