### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by nelis249** [Einstein42/myq-garage#22]
Not really an issue, more of a question. I've had code running against the myQ API and as of a week or so ago (Nov 20ish) the API stopped responding resulting in a 216 Unauthorized. I'm wondering if you've hit the same result.

**Comment by brbeaird** [comment]
I had to update my own integration about a month ago. The security token needs to be sent in the header now, not just as a query string variable. MyQ had gradually been making changes, and this has affected more and more people over time.

Here's the commit from my integration: https://github.com/brbeaird/SmartThings_MyQ/commit/0407ad141d982b92f04362b523554b75c2090fdb

**Comment by nelis249** [comment]
Ah that's it. I see it in the android apk. Thank you sir.
