### ISSUE TITLE
Did they change the API again?

### ISSUE THREAD

**Issue by swails** [Einstein42/myq-garage#23]
All of a sudden I'm getting unauthorized exceptions :(

**Comment by brbeaird** [comment]
I had to update my own integration about a month ago. The security token needs to be sent in the header now, not just as a query string variable. MyQ had gradually been making changes, and this has affected more and more people over time.

Here's the commit from my integration: brbeaird/SmartThings_MyQ@0407ad1

**Comment by swails** [comment]
Thanks!  Adding them to the header worked.

It seems like MyQ might have blacklisted some sources as well.  I can run a Python script from my house and the garage will now open or close in response.  But if I run the same exact code from an AWS Lambda function, I get connection errors claiming they were "reset by peer".

How does your SmartThings binding work?  Is the request sent locally from your bridge, or from ST's central servers? (I use your binding also and it's not working atm)

**Comment by brbeaird** [comment]
The request is sent from ST's servers. It also still seems to work from any local machine I try if I try to send just a test command, but it's definitely possible they've started blocking from places like AWS.

**Comment by swails** [comment]
Worked like a charm!
