### ISSUE TITLE
PyPi?

### ISSUE THREAD

**Issue by mike-seagull** [Einstein42/myq-garage#24]
great script btw...
Any chances of this being added to PyPi?
It would be awesome if we could just import the "MyQ" class.
Also, I'm than willing to contribute code to help make this possible.

**Comment by Einstein42** [comment]
Sounds like a plan. I wrote this years ago and luckily some other folks have taken up the mantle. I've got several other projects that unfortunately have to come first, but I'd like to clean this up and get it on PyPi shortly. Give me a couple of weeks.

**Comment by mike-seagull** [comment]
Sounds good. Let me know what I can do to help.
