### ISSUE TITLE
USE_ISY variable is not reading in as a boolean

### ISSUE THREAD

**Issue by cmgj74** [Einstein42/myq-garage#3]
USE_ISY variable is not reading in as a boolean

I don't have ISY, so I set it to False.

It still thought it was set to True.

per this:
http://stackoverflow.com/questions/12750778/booleans-in-configparser-always-return-true

USE_ISY = config.get('ISYConfiguration', 'USE_ISY')
should be:
USE_ISY = config.getboolean('ISYConfiguration', 'USE_ISY')

Thanks!

**Comment by Einstein42** [comment]
Go ahead and fix it, I'll approve a merge request. I apologize, but I haven't had time to work on this is a long time.

**Comment by cmgj74** [comment]
Ok, I fixed it.
